config/routes.rb
Rails.application.routes.draw do

  match '/pusher/auth' => 'pusher#auth', via: :post
  root "home#index"

  get 'home/index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
    get 'auth/:provider/callback', to: 'sessions#omniauthcreate'
    get 'auth/failure', to: redirect('/')
  get '/users/teacherize', to: 'users#teacherize'
  get '/users/:id/calendar', to: 'users#calendar'
  get '/userjson', to: 'users#current_user_json'
  get '/teachersjson', to: 'users#teachers_json'
  post '/users/:id/availability', to: 'users#set_availability'
  get '/rerender/availability', to: 'users#rerender_availability'
  post '/users/becometeacher', to: 'users#becometeacher'
  post 'users/:id/edit', to: 'users#edit'
  resources :users, only: [:new, :create, :show, :update]
  get '/homepage', to: 'users#homepage'

  resources :subjects, only: [:new, :create, :index, :show]

  post '/skillsearch', to: 'skills#search'

  resources :skills, only: [:new, :create, :index, :show]
  resources :connections, only: [:new, :show, :create, :update, :destroy]
  resources :conversations, only: [:new, :show, :create] do
    resources :messages, only: [:new, :create, :index, :show]
  end

  get '/lessons/json', to: 'lessons#lesson_json'
  post '/lessons/render_options', to: 'lessons#render_options'
  post '/lessons/:id/approve', to: 'lessons#approve'
  post '/lessons/:id/reject', to: 'lessons#reject'
  get '/lessons/:id/chat', to: 'lessons#chat'
  resources :lessons, only: [:create, :show, :update, :delete]
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


  before_filter :authenticate!

  def new
    @conversation = Conversation.find(params[:conversation_id])
    @message = Message.new(user_id: params[:user_id], conversation_id: params[:conversation_id])
  end

  def create
    conversation = Conversation.find(params[:conversation_id])
    @message = conversation.messages.build(message_params)
    @message.user_id = current_user.id
    @message.save
    @recipient = conversation.recipient
    UserMailer.message_email(@recipient).deliver_later


    # redirect_to @conversation
    respond_to do |format|
      format.html {redirect_to conversation}
      format.js {}
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :user_id, :conversation_id)
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_message.html.erb
    <div class="panel-heading">
      <strong><%= message.user.name %> wrote:</strong> <br>
      <%= message.created_at %>
    </div>
    <div class="panel-body">
      <%= message.body %>
    </div>

app/views/messages/_message_button.html.erb
<% if !Conversation.between(current_user.id, recipient.id).present? %>
  <%= link_to "Message", conversations_path(:controller => "conversations", :action => "create", :conversations => {:sender_id => current_user.id, :recipient_id => recipient.id}), :method=> :post, class: "btn btn-primary btn-xs" %>
<% else %>
  <% conversation = Conversation.between(current_user.id, recipient.id).first %>
  <%= link_to "Message", conversation_path(conversation), class: "btn btn-primary btn-xs" %>
<% end %>

app/views/messages/_new.html.erb
<%= form_for @message, :remote => true do |f| %>
  <div class="form-group">

      <%= f.label :body, "New message" %>
      <%= f.text_area :body, class: "form-control", rows: 3 %>
      <%= hidden_field_tag(:user_id, current_user.id) %>
      <%= hidden_field_tag(:conversation_id, @conversation.id) %>
      <br>
    <%= f.submit "Send", class: "btn btn-default btn-primary" %>

  </div>
<% end %>

app/views/messages/create.js.erb
$('.conversation').append("<%= j(render @message) %>")
$('.form-control').val('');

app/views/messages/show.html.erb
<%= @message.body %>
<%= @message.sender_id %>
<%= @message.receiver_id %>