config/routes.rb
Rails.application.routes.draw do

  match '/pusher/auth' => 'pusher#auth', via: :post
  root "home#index"

  get 'home/index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
    get 'auth/:provider/callback', to: 'sessions#omniauthcreate'
    get 'auth/failure', to: redirect('/')
  get '/users/teacherize', to: 'users#teacherize'
  get '/users/:id/calendar', to: 'users#calendar'
  get '/userjson', to: 'users#current_user_json'
  get '/teachersjson', to: 'users#teachers_json'
  post '/users/:id/availability', to: 'users#set_availability'
  get '/rerender/availability', to: 'users#rerender_availability'
  post '/users/becometeacher', to: 'users#becometeacher'
  post 'users/:id/edit', to: 'users#edit'
  resources :users, only: [:new, :create, :show, :update]
  get '/homepage', to: 'users#homepage'

  resources :subjects, only: [:new, :create, :index, :show]

  post '/skillsearch', to: 'skills#search'

  resources :skills, only: [:new, :create, :index, :show]
  resources :connections, only: [:new, :show, :create, :update, :destroy]
  resources :conversations, only: [:new, :show, :create] do
    resources :messages, only: [:new, :create, :index, :show]
  end

  get '/lessons/json', to: 'lessons#lesson_json'
  post '/lessons/render_options', to: 'lessons#render_options'
  post '/lessons/:id/approve', to: 'lessons#approve'
  post '/lessons/:id/reject', to: 'lessons#reject'
  get '/lessons/:id/chat', to: 'lessons#chat'
  resources :lessons, only: [:create, :show, :update, :delete]
end

app/models/skill.rb
class Skill < ActiveRecord::Base

  searchkick


  validates_uniqueness_of :name
  validates_presence_of :subject_id

  belongs_to :subject
  has_many :teacher_skills
  has_many :teachers, through: :teacher_skills, class_name: "User"


  def search_index_json
    [{value: self.name, data:"/skills/#{self.id}"}]
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def new
    @skill = Skill.new
  end

  def create
    skill = current_user.skills.create(skill_params)
    Skill.reindex if skill.save
    respond_to do |format|
      format.js{}
    end
  end

  def index
    @skills = Skill.all
    respond_to do |format|
      format.html{}
      format.json{render json: @skills.map{|skill| skill.search_index_json}.compact.flatten}
    end
  end

  def show
    @skill = Skill.find(params[:id])
  end

  def search
    @skills = Skill.search(params[:query]).map {|result| result}
    @query = params[:query]
  end



  private
  def skill_params
    params.require(:skill).permit(:name, :description, :subject_id)
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<div class="skill_form">
  <%= form_for @skill, remote: true, :role => "form" do |f|%>
    <div class="skill_name form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control input-sm" %>
    </div>
    <div class="skill_description form-group">
      <%= f.label :description %>
      <%= f.text_field :description, :class => "form-control input-sm" %>
    </div>
    <p class="text-primary">Subject area</p>
    <div class="skill_subject form-group">
      <%= f.collection_radio_buttons(:subject_id, Subject.all, :id, :name) do |b| %>
          <div class="radio custom">
            <%= b.label do %>
            <%=b.radio_button + b.text%>
            <% end %>
          </div>
      <% end %>
    </div>
    <%= hidden_field_tag(:original_page, return_to) %>
    <%= f.submit :class => 'btn btn-success btn-xs'  %>

  <% end %>
</div>

app/views/skills/_index.html.erb
<p>Skills in this subject:</p>
<ul>
  <% locals[:skills].each do |skill| %>
    <li><%= link_to "#{skill.name}", skill_path(skill) %></li>
  <% end %>
</ul>

app/views/skills/_skill.html.erb
<li> <%= link_to skill.name, skill %> </li>

app/views/skills/_skill_by_subject.html.erb
<h3 class="cs-heading top-space less-space skill">Skills in this subject:</h3>

        <div class="row">
          <div class="col-lg-8 col-md-10">
            <div class="panel-group" id="accordion-skills">
              <% locals[:skills].each do |skill| %>
              <div class="panel">
                <%= link_to ("#collapse#{skill.id}"), :class => "panel-heading", "data-toggle" => "collapse", "data-parent" => "#accordion-skills" do %>
                  <%= skill.name %>
                  <div class="indicator"><div class="icon"><span class="hr-line"></span><span class="vr-line"></span></div></div>
                <% end %>

                <div id="collapse<%= skill.id  %>" class="panel-collapse collapse">
                  <div class="panel-body">
                    <p><%= skill.description %></p>
                    <h6>People with this skill:</h6>
                    <ul>
                      <% skill.teachers.each do |teacher| %>
                      <li><%= link_to teacher.name, teacher %></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
              <% end %>

            </div>
          </div>
        </div>

app/views/skills/_skills.html.erb
<div class="row">
    <div class="col-lg-8 col-md-10">
      <div class="panel-group" id="accordion-skills">
        <% @skills.each do |skill| %>
        <div class="panel">
          <%= link_to ("#collapse#{skill.id}"), :class => "panel-heading", "data-toggle" => "collapse", "data-parent" => "#accordion-skills" do %>
            <%= skill.name %>
            <div class="indicator"><div class="icon"><span class="hr-line"></span><span class="vr-line"></span></div></div>
          <% end %>

          <div id="collapse<%= skill.id  %>" class="panel-collapse collapse">
            <div class="panel-body">
              <p><%= skill.description %></p>
              <h6>People with this skill:</h6>
              <ul>
                <% skill.teachers.each do |teacher| %>
                <li><%= link_to teacher.name, teacher %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
  </div>

app/views/skills/_skillsearch.html.erb
<%= form_tag skillsearch_path, class: "navbar-form navbar-left" do%>
  <div class="form-group">
    <%= text_field_tag :query, nil, placeholder: "Search for Skills",class: "form-control" %>
  </div>
  <%= submit_tag "Search", class: "btn btn-default"%>
<% end %>

app/views/skills/create.js.erb
debugger;

$('#user_skills').empty()
$('#user_skills').append("<%= j render partial: 'users/skills/teacher_skills', locals: {teacher: current_user} %>")

$('#skills_selector').empty()
$('#skills_selector').append("<%= j render partial: 'users/skills/skill_selector', locals: {user: current_user}%>")

app/views/skills/index.html.erb
<h1>All the Skills</h1>
<%= link_to "Create a new skill", new_skill_path %>
<ul>
  <% @skills.each do |skill| %>
   <!--Not showing the skill name. Need to work on that later-->
    <li><%= link_to skill.name, skill %></li>
  <% end %>
</ul>

app/views/skills/new.html.erb
<%= render "form" %>

app/views/skills/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Search Results for "<%= @query %>"</h2>
    </div>
    <div class="col-md-8">
      <br>
      <%= render "skills" %>
    </div>
  </div>
</div>

app/views/skills/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2 class="text-center cs-heading"><%= @skill.name %></h2>
      <%= image_tag("subtb.jpg", :class => "img-circle img-center") %>
    </div>
    <div class="col-md-8">
      <br>
      <h3><%= @skill.description %></h3>
      <% if @skill.teachers %>
        <p>Teachers with this skill:</p>
        <ul>
          <% @skill.teachers.each do |teacher| %>
          <li><%= link_to teacher.user_name, teacher %></li>
          <% end %>
        </ul>
      <% else %>
        <p>There are no teachers with this skill yet.</p>
      <% end %>
    </div>
  </div>
</div>