config/routes.rb
Rails.application.routes.draw do

  match '/pusher/auth' => 'pusher#auth', via: :post
  root "home#index"

  get 'home/index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
    get 'auth/:provider/callback', to: 'sessions#omniauthcreate'
    get 'auth/failure', to: redirect('/')
  get '/users/teacherize', to: 'users#teacherize'
  get '/users/:id/calendar', to: 'users#calendar'
  get '/userjson', to: 'users#current_user_json'
  get '/teachersjson', to: 'users#teachers_json'
  post '/users/:id/availability', to: 'users#set_availability'
  get '/rerender/availability', to: 'users#rerender_availability'
  post '/users/becometeacher', to: 'users#becometeacher'
  post 'users/:id/edit', to: 'users#edit'
  resources :users, only: [:new, :create, :show, :update]
  get '/homepage', to: 'users#homepage'

  resources :subjects, only: [:new, :create, :index, :show]

  post '/skillsearch', to: 'skills#search'

  resources :skills, only: [:new, :create, :index, :show]
  resources :connections, only: [:new, :show, :create, :update, :destroy]
  resources :conversations, only: [:new, :show, :create] do
    resources :messages, only: [:new, :create, :index, :show]
  end

  get '/lessons/json', to: 'lessons#lesson_json'
  post '/lessons/render_options', to: 'lessons#render_options'
  post '/lessons/:id/approve', to: 'lessons#approve'
  post '/lessons/:id/reject', to: 'lessons#reject'
  get '/lessons/:id/chat', to: 'lessons#chat'
  resources :lessons, only: [:create, :show, :update, :delete]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user= User.new
    @subjects = Subject.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row learnFooter">
      <div class="col-lg-12">
        <h2 class="text-center text-light">There's a whole world of learning to explore.</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <p class="copyright">&copy; 2016 Our Project Team. All Rights Reserved. Made with <3 at the Flatiron School</p>
      </div>
    </div>
  </div>
</footer>

app/views/home/index.html.erb
<div id="preloader"><div id="spinner"></div></div>
<section class="hero">
  <div class="container">
        <!--Hero Slider-->
    <div class="row">
      <div class="hero-slider">
        <div class="slide first-slide">
          <div class="col-lg-5 col-md-5 col-sm-5 animated">

            <h2 style="margin-top:50px;" class="text-light text-left">Connect. Learn. Teach.</h2>
            <p>Coding. Graphic design. Desktop publishing.</p>
            <p>There's a whole world of hard skills out there waiting for you.  With Edifi, bringing teachers and learners together has never been simpler. </p>
            <% if !logged_in? %>
              <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#signUpModal">Sign Up</a>
            <% end %>
              <%= link_to "Browse Subjects", subjects_path, class: "btn btn-primary" %>
            <br><br><br><br><br><br><br><br><br>

          </div>
        </div>
      </div>
    </div><!--Close Hero Slider-->
  </div>
</section><!--Close Hero-->
<section class="page-block" id="gallery">
  <div class="container">
    <div class="row page-header">
      <h2>Browse Subjects</h2>
      <span>Click to learn more</span>
    </div>
    <%= render "subjects/index" %>
  </div>

</section>
<!-- sign up modal -->
<div class="light-skin modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Create an Account</h4>
      </div>
      <div class="modal-body">
        <%= render "users/form" %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->